apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
 name: k8s-multi-com-tls
spec:
 secretName: k8s-multi-com
 issuerRef:
  name: letsencrypt-prod
  kind: ClusterIssuer
 commonName: achaigne.com
 dnsNames:
  - achaigne.com
  - www.achaigne.com
 acme:
  config:
   - http01:
      ingressClass: nginx
     domains:
      - achaigne.com
      - www.achaigne.com