apiVersion: cert-manager.io/v1alpha
kind: ClusterIssuer
metadata:
 name: letsencrypt-prod
spec:
 acme:
  server: https://acme-v02.api.letsencrypt.org/directory
  email: 'adrien.chaigne@gmaail.com'
  privateKeySecretRef:
   name: letsencrypt-prod
  http01: {}
  